In [10]:
import matplotlib.pyplot as plt 
import numpy as np 

#This toy example is just a grid-word. An example of the grid-world may be a 4x4 grid, where movment costs -1 points
#Reacing index 0,0 means a terminal state, and all future reward is 0

#The grid world is represented as zeros where nothing is present, and 1 where the agent is present
grid = np.zeros((4,4))
grid[2,2] = 1 
print(grid)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [188]:
def index_displacement_for_action(action): 
    if action == 0: 
        return (0, -1)
    elif action == 1: 
        return (0, 1)
    elif action == 2: 
        return (-1, 0)
    elif action == 3: 
        return (1, 0)
    else:
        return (0, 0)

#Policy: the policy will be to choose a random available action 
#The actions are as follows: [up, down, left, right, nothing] = 0,1,2,3,4 indices. 
#When something in the action matrix is 1, it is possible to take this action. 0 means impossible. 
action_matrix = np.ones((4,4,5))
action_matrix[0,:,2] = 0
action_matrix[:,0,0] = 0
action_matrix[:,3,1] = 0
action_matrix[3,:,3] = 0
action_matrix[:,:,4] = 0
action_matrix[0,0] = np.array([0,0,0,0,1])
action_matrix[3,3] = np.array([0,0,0,0,1])

#Creating the reward matrix
reward_matrix = np.ones((4,4))*-1
reward_matrix[0,0] = 0
reward_matrix[3,3] = 0


In [189]:
def index_displacement_for_action(action): 
    if action == 0: 
        return (0, -1)
    elif action == 1: 
        return (0, 1)
    elif action == 2: 
        return (-1, 0)
    elif action == 3: 
        return (1, 0)
    else:
        return (0, 0)
    

In [202]:
value_matrix = np.zeros((4,4))
new_value_matrix = value_matrix.copy()
for y in range(0,4): 
    for x in range(0,4): 
        action_possibilities = np.where(action_matrix[x,y]==1)[0]
        action_probability = 1/len(action_possibilities) #Same probability for each action
        
        states = [] #States the agent can move to from current state
        for action in action_possibilities:
            dis = index_displacement_for_action(action)
            states.append( (x+dis[0], y+dis[1]) )
        
        value = 0
        for state in states: 
            value += value_matrix[state]*action_probability
        new_value_matrix[x,y] = value + reward_matrix[x,y]
        
value_matrix = new_value_matrix.copy()
value_matrix

array([[ 0., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1.,  0.]])

In [210]:
value_matrix = np.zeros((4,4))
new_value_matrix = value_matrix.copy()
for i in range(10000):
    value_matrix = new_value_matrix.copy()
    for y in range(0,4): 
        for x in range(0,4): 
            action_possibilities = np.where(action_matrix[x,y]==1)[0]
            action_probability = 1/len(action_possibilities) #Same probability for each action

            states = [] #States the agent can move to from current state
            for action in action_possibilities:
                dis = index_displacement_for_action(action)
                states.append( (x+dis[0], y+dis[1]) )

            value = 0
            for state in states: 
                value += value_matrix[state]*action_probability
            new_value_matrix[x,y] = value + reward_matrix[x,y]
            
    value_matrix = new_value_matrix.copy()

value_matrix

array([[  0. , -11. , -15.5, -16.5],
       [-11. , -14.5, -16. , -15.5],
       [-15.5, -16. , -14.5, -11. ],
       [-16.5, -15.5, -11. ,   0. ]])

In [193]:
for i in range(1000):
    for y in range(0,4): 
        for x in range(0,4): 
            new_value_matrix = value_matrix
            action_possibilities = np.where(action_matrix[x,y]==1)[0]
            action_probability = 1/len(action_possibilities) #Same probability for each action

            states = []
            for action in action_possibilities:
                dis = index_displacement_for_action(action)
                states.append( (x+dis[0], y+dis[1]) )

            value = 0
            for state in states: 
                value += value_matrix[state]*action_probability

            new_value_matrix[x,y] = value + reward_matrix[x,y]

    value_matrix = new_value_matrix
value_matrix   

array([[  0. , -11. , -15.5, -16.5],
       [-11. , -14.5, -16. , -15.5],
       [-15.5, -16. , -14.5, -11. ],
       [-16.5, -15.5, -11. ,   0. ]])